### ISSUE TITLE
(S3) How high a voltage will cause a regulator to break?

### ISSUE THREAD

**Issue by thelionroars** [664306x/swin.edu.au-esp8266#21]
"remember that the higher the voltage the more heat the regulator will create and if it gets to hot it may break."

How high a voltage are we looking at here? Over 12 volts?

**Comment by adsmji4** [comment]
Any voltage above recomeded will shorten it's life span. However it will still work until it over heats

**Comment by adsmji4** [comment]
The one on the board us rated for 5v down to 3.3

**Comment by thelionroars** [comment]
This appears to be resolved, closing.
