### ISSUE TITLE
The esptool.py in the installer toolchain cannot be used to flash

### ISSUE THREAD

**Issue by edwinwongcm** [664306x/swin.edu.au-esp8266#22]

**Comment by edwinwongcm** [comment]
I was able to flash using the main source
https://github.com/themadinventor/esptool

**Comment by thelionroars** [comment]
I've only tried it on Linux so far. What happens when you try it on Windows after installation?

**Comment by edwinwongcm** [comment]
![esptool](https://cloud.githubusercontent.com/assets/11514479/7512364/c728e190-f4ef-11e4-8472-07493a6d5071.jpg)

**Comment by edwinwongcm** [comment]
u were able to run it smoothly? i'm getting syntax error on the esptool.py file

**Comment by edwinwongcm** [comment]
not going to include
