### ISSUE TITLE
Issues with Section 8

### ISSUE THREAD

**Issue by 664306x** [664306x/swin.edu.au-esp8266#9]
1. It needs to be proof-read (many sentences are awkward).
2. All assumed knowledge (beyond what is stated in the target audience) needs to be linked back to the relevant section in the guide.
3. The guide is very specific to esp8266_12. Either make it generic (for example using led and cables, not the leds on the eval board) or clearly state that it only applies to esp8266_12.
4. if the guide assumes the esp8266 is running nodeMCU firmware, at the start state that.
5. outcomes should be the first thing under the title.
6. define the wifi modes. You state the three modes and how to set them, but not what they actually mean.

**Comment by edwinwongcm** [comment]
1. Need to discuss which sentences are awkward
2. Fixed
3. Not done
4. Fixed
5. Fixed
6. Was already included but need to show to confirm
